version: '3.9'
services:
  bot:
    image: batman-bot
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TOKEN=${TOKEN}
    ports:
      - ${PORT}:3000
    env_file:
      - .env